---
title: "filter_join"
author: "Bryan Zirkle"
date: "10/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Attach Pacakges
```{r packages}
library(tidyverse)
library(readxl)
library(here)
library(kableExtra)
```

## Load Data
```{r dataload}
fish <- read_csv(here("data","fish.csv"))
kelp_abur <- read_excel(here("data","kelp.xlsx"),sheet = "abur")
```

## Filter Data
```{r filters}
fish_garibaldi <- fish %>% 
  filter(common_name == "garibaldi")

fish_mohk <- fish %>% 
  filter(site == "mohk")

fish_over50 <- fish %>% 
  filter(total_count >= 50)

##Filter 'OR'

fish_3sp <- fish %>% 
  filter(common_name == "garibaldi" |
           common_name == "blacksmith" |
           common_name == "black surfperch")

fish_3sp <- fish %>% 
  filter(common_name %in% c("garibaldi", "blacksmith", "black surfperch"))

fish_gar_2016 <- fish %>% 
  filter(year == 2016 | common_name == "garibaldi")

##Filter 'AND'

aque_2018 <-  fish %>% 
  filter(year == 2018, site == "aque")

aque_2018 <-  fish %>% 
  filter(year == 2018 & site == "aque")

aque_2018 <-  fish %>% 
  filter(year == 2018) %>% 
  filter(site == "aque")

##Filter 'AND' & 'OR'

low_gb_wr <- fish %>% 
  filter(common_name == "garibaldi" | common_name == "rock wrasse") %>% 
  filter(total_count <= 10)

##Filter 'Detect' by string

fish_bl <- fish %>% 
  filter(str_detect(common_name, pattern = "black"))

fish_it <-  fish %>% 
  filter(str_detect(common_name, pattern = "it"))

##Filter 'Exclude' by string

fish_bl_exclude <- fish %>% 
  filter(str_detect(common_name,pattern = "black", negate = T))
```

##Join Data
```{r joins}
##Full Join
abur_kelp_fish <- kelp_abur %>% 
  full_join(fish, by = c("year","site"))

##Left Join
kelp_fish_left <- kelp_abur %>% 
  left_join(fish,  by = c("year","site"))

##Inner join
kelp_fish_injoin <-  kelp_abur %>% 
  inner_join(fish, by = c("year","site"))
```

##Combined Steps
```{r combined}
my_fish_join <- fish %>% 
  filter(year == 2017, site == "abur") %>% 
  left_join(kelp_abur, by = c("year","site")) %>% 
  mutate(fish_per_frond = total_count/total_fronds)
```

##Knit Better Looking Table
```{r kable}
my_fish_join %>% 
  kable(align = "c") %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = F,
                position = "center")
```