---
title: '"Creating graphs in R with ''ggplot2'''
author: "Bryan Zirkle"
date: "10/16/2020"
output: html_document
---

# Plots with ggplot2

```{r calls, echo=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(scales)
```

```{r read, echo=FALSE}
ca_np <- read.csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r line plot}
ggplot(data = ci_np, aes(x=year, y=visitors))+
  geom_line()
```

```{r store base plot}
gg_base <- ggplot(data = ci_np, aes(x=year,y=visitors))
```

```{r scatter plot}
gg_base +
  geom_point()
```

```{r column plot}
gg_base+
  geom_col()
```

```{r area plot}
gg_base +
  geom_area()
```

```{r line plot viz}
gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )
```

```{r scatter plot viz}
gg_base + 
  geom_point(
    color = "purple",
    pch = 17,
    size = 4,
    alpha = 0.5
  )
```

```{r column plot viz}
gg_base +
  geom_col(
    color = "royalblue",
    fill = "skyblue",
    linetype = "solid",
    size = 0.5,
    alpha = 0.75,
  )
```

```{r scatter plot var viz}
gg_base +
  geom_point(
    aes(size = visitors,
    color = visitors),
    alpha = 0.5
  ) +
  theme_minimal()
```

```{r column plot var viz}
gg_base +
  geom_col(
    aes(fill=visitors)
  )
```

```{r line plot lab viz}
gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  ) +
  scale_y_continuous(labels = comma)
```

```{r line plot multi viz}
gg_base +
  geom_line(color = "purple") +
  geom_point(color = "orange",
             aes(size = year),
             alpha = 0.5)
```

```{r column plot multi viz}
gg_base +
  geom_col(fill = "orange",
           color = "purple") +
  geom_line(color = "green")
```

```{r store 2nd base plot}
gg_np <- ggplot(data = ca_np, aes(year, visitors, group = park_name)) +
  scale_y_continuous(labels = comma)
```

```{r facet line plots}
gg_np +
  geom_line(show.legend = F) +
  theme_bw() +
  labs(x = "Year", y = "Annual Visitors") +
  facet_wrap(~park_name)
```

```{r fact column plots}
gg_np +
  geom_col(show.legend = F) +
  theme_bw() +
  labs(x = "Year", y = "Annual Visitors") +
  facet_wrap(~park_name)
```

```{r ggsave export}
ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
```

